export const IMAGE_MAP = {
  // --- Megerősített, létező képfájlok ---
  "Iguanodon": require('../../assets/images/iguanodon.jpg'),
  "Megalosaurus": require('../../assets/images/megalosaurus.jpg'),
  "Baryonyx": require('../../assets/images/baryonyx.jpg'),
  "Hypsilophodon": require('../../assets/images/hypsilophodon.jpg'),
  "Europasaurus": require('../../assets/images/europasaurus.jpg'),
  "Plateosaurus": require('../../assets/images/plateosaurus.jpg'),
  "Cetiosaurus": require('../../assets/images/cetiosaurus.jpg'),
  "Camptosaurus": require('../../assets/images/camptosaurus.jpg'),
  "Valdosaurus": require('../../assets/images/valdosaurus.jpg'),
  "Mantellisaurus": require('../../assets/images/mantellisaurus.jpg'),
  "Neovenator": require('../../assets/images/neovenator.jpg'),
  "Scipionyx": require('../../assets/images/scipionyx.jpg'),
  "Draconyx": require('../../assets/images/draconyx.jpg'),
  "Torvosaurus": require('../../assets/images/torvosaurus.jpg'),
  "Lourinhanosaurus": require('../../assets/images/lourinhanosaurus.jpg'),
  "Liliensternus": require('../../assets/images/liliensternus.jpg'),
  "Rhabdodon": require('../../assets/images/rhabdodon.jpg'),
  "Magyarosaurus": require('../../assets/images/magyarosaurusb.jpg'),
  "Zalmoxes": require('../../assets/images/zalmoxes.jpg'),
  "Lusotitan": require('../../assets/images/lusotitan.jpg'),
  "Allosaurus": require('../../assets/images/allosaurus_eu.jpg'),
  "Thecodontosaurus": require('../../assets/images/thecodontosaurus.jpg'),
  "Concavenator": require('../../assets/images/concavenator.jpg'),
  "Pelecanimimus": require('../../assets/images/pelecanimimus.jpg'),
  "Arcovenator": require('../../assets/images/arcovenator.jpg'),
  "Hungarosaurus": require('../../assets/images/hungarosaurus.jpg'),
  "Ajkaceratops": require('../../assets/images/ajkaceratops.jpg'),
  "Pneumatoraptor": require('../../assets/images/pneumatoraptor_fodori.jpg'),
  "Mochlodon": require('../../assets/images/mochlodon_vorosi.jpg'),
  "Telmatosaurus": require('../../assets/images/telmatosaurus.jpg'),
  "Struthiosaurus": require('../../assets/images/struthiosaurus.jpg'),
  "Petrustitan": require('../../assets/images/petrustitan.jpg'),
  "Uriash": require('../../assets/images/uriash_kadici.jpg'),
  "Komlosaurus": require('../../assets/images/komlosaurus.jpg'),
  "Hylaeosaurus": require('../../assets/images/hylaeosaurus.jpg'),
  "Spinosaurus": require('../../assets/images/spinosaurus.jpg'),
  "Gigantoraptor": require('../../assets/images/gigantoraptor.jpg'),
  "Nigersaurus": require('../../assets/images/nigersaurus.jpg'),
  "Compsognathus": require('../../assets/images/compsognathus.jpg'),
  "Therizinosaurus": require('../../assets/images/therizinosaurus.jpg'),
  "Pantydraco": require('../../assets/images/pantydraco.jpg'),
  "Hatzegopteryx": require('../../assets/images/hatzegopteryx.jpg'),
  "Balaur": require('../../assets/images/balaur.jpg'),
  "Polacanthus": require('../../assets/images/polacanthus.jpg'),
  "Eustreptospondylus": require('../../assets/images/eustreptospondylus.jpg'),
  "Miragaia": require('../../assets/images/miragaia.jpg'),
  "Carcharodontosaurus": require('../../assets/images/carcharodontosaurus.jpg'),
  "Suchomimus": require('../../assets/images/suchomimus.jpg'),
  "Majungasaurus": require('../../assets/images/majungasaurus.jpg'),
  "Ouranosaurus": require('../../assets/images/ouranosaurus.jpg'),
  "Scelidosaurus": require('../../assets/images/scelidosaurus.jpg'),
  "Archaeopteryx": require('../../assets/images/archaeopteryx.jpg'),
  "Euoplocephalus": require('../../assets/images/euoplocephalus.jpg'),
  // --- name_hu lista alapján még hiányzó fájlok ---
  // Ezek a kulcsok léteznek az adatbázisban (name_hu), de nincs hozzájuk
  // megerősített kép a assets/images mappában. Kikommentelve maradnak,
  // amíg a fájl fel nem kerül — a lookup ("IMAGE_MAP[name] || null")
  // ettől nem törik el, csak kép nélkül jelenik meg a kártya.
  // "Leaellynasaura": require('../../assets/images/leaellynasaura.jpg'),
  // "Edmontosaurus": require('../../assets/images/edmontosaurus.jpg'),
  // "Gallimimus": require('../../assets/images/gallimimus.jpg'),
  // "Kentrosaurus": require('../../assets/images/kentrosaurus.jpg'),
  // "Albertosaurus": require('../../assets/images/albertosaurus.jpg'),
  // "Amargasaurus": require('../../assets/images/amargasaurus.jpg'),
  // 
  // "Brachiosaurus": require('../../assets/images/brachiosaurus.jpg'),
  // "Masiakasaurus": require('../../assets/images/masiakasaurus.jpg'),
  // "Qantassaurus": require('../../assets/images/qantassaurus.jpg'),
  // "Neuquenosaurus": require('../../assets/images/neuquenosaurus.jpg'),
  // "Giganotosaurus": require('../../assets/images/giganotosaurus.jpg'),
  // "Stegosaurus": require('../../assets/images/stegosaurus.jpg'),
  // "Mussaurus": require('../../assets/images/mussaurus.jpg'),
  // "Argentinosaurus": require('../../assets/images/argentinosaurus.jpg'),
  // "Tyrannotitan": require('../../assets/images/tyrannotitan.jpg'),
  // "Diplodocus": require('../../assets/images/diplodocus.jpg'),
  // "Giraffatitan": require('../../assets/images/giraffatitan.jpg'),
  // "Tarbosaurus": require('../../assets/images/tarbosaurus.jpg'),
  // "Apatosaurus": require('../../assets/images/apatosaurus.jpg'),
  // "Patagotitan": require('../../assets/images/patagotitan.jpg'),
  // "Xenotarsosaurus": require('../../assets/images/xenotarsosaurus.jpg'),
  // "Saltasaurus": require('../../assets/images/saltasaurus.jpg'),
  // "Gasparinisaura": require('../../assets/images/gasparinisaura.jpg'),
  // "Camarasaurus": require('../../assets/images/camarasaurus.jpg'),
  // "Ankylosaurus": require('../../assets/images/ankylosaurus.jpg'),
  // "Triceratops": require('../../assets/images/triceratops.jpg'),
  // "Parasaurolophus": require('../../assets/images/parasaurolophus.jpg'),
  // "Protoceratops": require('../../assets/images/protoceratops.jpg'),
  // "Tyrannosaurus": require('../../assets/images/tyrannosaurus.jpg'),
  // "Massospondylus": require('../../assets/images/massospondylus.jpg'),
  // "Gorgosaurus": require('../../assets/images/gorgosaurus.jpg'),
  // "Troodon": require('../../assets/images/troodon.jpg'),
  // "Sinosauropteryx": require('../../assets/images/sinosauropteryx.jpg'),
  // "Noasaurus": require('../../assets/images/noasaurus.jpg'),
  // "Alvarezsaurus": require('../../assets/images/alvarezsaurus.jpg'),
  // "Ligabuesaurus": require('../../assets/images/ligabuesaurus.jpg'),
  // "Irritator": require('../../assets/images/irritator.jpg'),
  // "Australotitan": require('../../assets/images/australotitan.jpg'),
  // "Muttaburrasaurus": require('../../assets/images/muttaburrasaurus.jpg'),
  // "Oviraptor": require('../../assets/images/oviraptor.jpg'),
  // "Styracosaurus": require('../../assets/images/styracosaurus.jpg'),
  // "Ornithomimus": require('../../assets/images/ornithomimus.jpg'),
  // "Alioramus": require('../../assets/images/alioramus.jpg'),
  // "Struthiomimus": require('../../assets/images/struthiomimus.jpg'),
  // "Utahraptor": require('../../assets/images/utahraptor.jpg'),
  // "Pentaceratops": require('../../assets/images/pentaceratops.jpg'),
  // "Coelophysis": require('../../assets/images/coelophysis.jpg'),
  // "Chubutisaurus": require('../../assets/images/chubutisaurus.jpg'),
  // "Velociraptor": require('../../assets/images/velociraptor.jpg'),
  // "Nagatitan": require('../../assets/images/nagatitan.jpg'),
  // "Deinocheirus": require('../../assets/images/deinocheirus.jpg'),
  // "Australovenator": require('../../assets/images/australovenator.jpg'),
  // "Deinonychus": require('../../assets/images/deinonychus.jpg'),
  // "Bauxitornis": require('../../assets/images/bauxitornis.jpg'),
  // "Psittacosaurus": require('../../assets/images/psittacosaurus.jpg'),
  // "Buitreraptor": require('../../assets/images/buitreraptor.jpg'),
  // "Diamantinasaurus": require('../../assets/images/diamantinasaurus.jpg'),
  // "Rhoetosaurus": require('../../assets/images/rhoetosaurus.jpg'),
  // "Bakonydraco": require('../../assets/images/bakonydraco.jpg'),
  // "Kunbarrasaurus": require('../../assets/images/kunbarrasaurus.jpg'),
};
